### ISSUE TITLE
tool call hangup

### ISSUE THREAD

**Issue by webcoderz** [SecretiveShell/MCP-Bridge#11]
pulled in latest commits with logging, now it seems the requests gets hung,

mcp-bridge  | generating config.json
mcp-bridge  | .........................
mcp-bridge  | starting mcp_bridge.........
mcp-bridge  | /usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "json" in "InitialSettings" shadows an attribute in parent "BaseSettings"
mcp-bridge  |   warnings.warn(
mcp-bridge  | 2024-12-20 20:26:46.890 | INFO     | config:<module>:21 - Loading config from config.json
mcp-bridge  | INFO:     Started server process [8]
mcp-bridge  | INFO:     Waiting for application startup.
mcp-bridge  | 2024-12-20 20:26:46.929 | DEBUG    | lifespan:lifespan:11 - Entered fastapi lifespan
mcp-bridge  | 2024-12-20 20:26:46.929 | DEBUG    | mcp_clients.McpClientManager:initialize:12 - Initializing MCP Client Manager
mcp-bridge  | 2024-12-20 20:26:46.929 | DEBUG    | mcp_clients.McpClientManager:construct_client:22 - Constructing client for command='uvx' args=['mcp-server-fetch'] env=None
mcp-bridge  | 2024-12-20 20:26:46.929 | DEBUG    | mcp_clients.StdioClientFactory:construct_stdio_client:8 - Constructing Stdio Server
mcp-bridge  | 2024-12-20 20:26:46.929 | DEBUG    | mcp_clients.ClientInstance:__init__:13 - Creating client instance for fetch
mcp-bridge  | 2024-12-20 20:26:46.929 | DEBUG    | lifespan:lifespan:13 - Initialized MCP Client Manager
mcp-bridge  | 2024-12-20 20:26:46.929 | DEBUG    | lifespan:lifespan:15 - Yielding lifespan
mcp-bridge  | INFO:     Application startup complete.
mcp-bridge  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
mcp-bridge  | Installed 31 packages in 6ms
mcp-bridge  | 2024-12-20 20:26:48.404 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:25 - finished initialise session for fetch
mcp-bridge  | 2024-12-20 20:26:58.410 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-20 20:27:08.417 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-20 20:27:18.427 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-20 20:27:28.438 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | INFO:     172.18.0.3:50206 - "GET /v1/models HTTP/1.1" 200 OK
mcp-bridge  | 2024-12-20 20:27:35.261 | DEBUG    | openai_clients.chatCompletion:chat_completions:36 - {"id":"chatcmpl-dc09fdc5840a413ba92c749b9489e698","object":"chat.completion","created":1734726453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"chatcmpl-tool-4da8d66990d8411d918ab9f0c76b4ca4","type":"function","function":{"name":"fetch","arguments":"{\"url\": \"https://example.com\", \"max_length\": \"1000\"}"}}]},"logprobs":null,"finish_reason":"tool_calls","stop_reason":128008}],"usage":{"prompt_tokens":477,"total_tokens":510,"completion_tokens":33,"prompt_tokens_details":null},"prompt_logprobs":null}
mcp-bridge  | 2024-12-20 20:27:35.261 | DEBUG    | openai_clients.chatCompletion:chat_completions:50 - finish reason: FinishReason1.tool_calls
mcp-bridge  | 2024-12-20 20:27:35.261 | DEBUG    | openai_clients.chatCompletion:chat_completions:55 - tool calls found
mcp-bridge  | 2024-12-20 20:27:35.261 | DEBUG    | openai_clients.chatCompletion:chat_completions:57 - tool call: fetch arguments: {'url': 'https://example.com', 'max_length': '1000'}
mcp-bridge  | 2024-12-20 20:27:38.450 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch

and stays here 

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/03ad90af-f7cc-4a87-b529-db4ce4b8732e" />

**Comment by webcoderz** [comment]
tried on another mcp server, one of tools worked , but another didnt, keeps getting hung up on pinging session ...

**Comment by SecretiveShell** [comment]
You are missing `tool call result for fetch:` from the logs, implying that the issue is when MCP-Bridge tries to call the fetch tool.

pinging the session should happen approx. every 30 seconds regardless of any tools being called.

So far I have been unable to reproduce this.

**Comment by webcoderz** [comment]
yea it seems its upstream, i removed fetch from servers and the other tool is doing completely fine. thanks

**Comment by SecretiveShell** [comment]
It may be that when you rebuilt the docker image it fetched a later version of the fetch tool from pypi, I would suggest having a look to see if any new versions have come out recently.

**Comment by webcoderz** [comment]
haha okay so tried a different site (https://something.com) and it works, seems example might block it now

**Comment by webcoderz** [comment]
another thing i just noticed, i gave it a vague name of a tool to call instead of being verbose, and it hung up but kept iterating over all of the tools and executing them and looping it through the LLM , maybe some sort of logic to cancel after x number of retries?

**Comment by SecretiveShell** [comment]
if you want to PR some of these features that would be great
