### ISSUE TITLE
Multiple responses

### ISSUE THREAD

**Issue by buryhuang** [SecretiveShell/MCP-Bridge#22]
It's a bit hard to describe, but it seems there may be duplicate responses.
I built a slack bot trying to use the mcp-bridge, it keep giving me duplicate response (results are different though, so it's likely multiple requests).

Once I switch back to use openai official url, the duplicated requests are gone.

Reporting to see if anyone is seeing similar.

EDIT:
I can reproduce it locally. And see the duplicate calls. I didn't do anything from client, but the server somehow call the tool request the second time:
`DEBUG:urllib3.connectionpool:https://api.hubapi.com:443 "GET /engagements/v1/engagements/recent/modified HTTP/1.1" 200 None`

```
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
Received ListToolsRequest
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6e050>
INFO:mcp.server:Processing request of type ListToolsRequest
DEBUG:mcp.server:Dispatching request of type ListToolsRequest
DEBUG:mcp.server:Response sent
Received ListToolsRequest
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f610>
INFO:mcp.server:Processing request of type ListToolsRequest
DEBUG:mcp.server:Dispatching request of type ListToolsRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6dab0>
INFO:mcp.server:Processing request of type CallToolRequest
DEBUG:mcp.server:Dispatching request of type CallToolRequest
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.hubapi.com:443
DEBUG:urllib3.connectionpool:https://api.hubapi.com:443 "GET /engagements/v1/engagements/recent/modified HTTP/1.1" 200 None
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6e2f0>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6e5f0>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
INFO:     44.203.247.244:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f370>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f5e0>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6e050>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f310>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6ecb0>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
Received ListToolsRequest
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f610>
INFO:mcp.server:Processing request of type ListToolsRequest
DEBUG:mcp.server:Dispatching request of type ListToolsRequest
DEBUG:mcp.server:Response sent
Received ListToolsRequest
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f310>
INFO:mcp.server:Processing request of type ListToolsRequest
DEBUG:mcp.server:Dispatching request of type ListToolsRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f370>
INFO:mcp.server:Processing request of type CallToolRequest
DEBUG:mcp.server:Dispatching request of type CallToolRequest
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.hubapi.com:443
DEBUG:urllib3.connectionpool:https://api.hubapi.com:443 "GET /engagements/v1/engagements/recent/modified HTTP/1.1" 200 None
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f280>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
INFO:     44.203.247.244:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6f610>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6ecb0>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0xffff9cd6e380>
INFO:mcp.server:Processing request of type PingRequest
DEBUG:mcp.server:Dispatching request of type PingRequest
DEBUG:mcp.server:Response sent
```

**Comment by SecretiveShell** [comment]
Which client are you using?

There is currently an issue with openwebui where the automatic title generation has the potential to call tools. If you use a prompt like `fetch http://example.com` it might fetch the site once during the regular completion and then during the title it will fetch the contents again. We were discussing tool calling profiles on the discord as a way to mitigate this during unwanted scenarios but no one has started an implementation yet.

What workflow (prompts) are you using?

There is no tool call history saved per request, so if you need the contents of a website to answer a question it will fetch the contents of the website again for each request. This is a limitation of the openai API spec. There might be a way to allow for a UUID to persist the hidden chat inside of MCP-Bridge but I have not looked into it yet.

Reproduction.

Can you please share the steps you took to reproduce the issue? I am hoping that it should be possible to do this via a local tool but the more information the better.

You might be able to mitigate the issue for now with a system prompt saying "only call tools in the last user message" but I have not tested this.

**Comment by buryhuang** [comment]
Thank you, that saved me tons of time debugging it! 
I'm using my own slack bot. As you suspected, I sent the last 20 messages to the bridge.
I didn't use any extra workflow (prompts).

The reason of my reproducing it probably because I keep sending the same message from slack to trigger the tool uses, so it'd be like following in the chat history. I'm not surprised it triggers multiple times :)
```
what's happening in my pipeline
what's happening in my pipeline
what's happening in my pipeline
what's happening in my pipeline
```

I did the following attempts:
- I added a system prompt of "You should only use tool use in the last message". That didn't work.
- I did a workaround to only send the last message. That works great (duh, now that I understood it).


From your discord discussion, what are the possible options?

**Comment by buryhuang** [comment]
Thank you much! That gave me a lot of info an keep me thinking.

Eventually, it turns out it's because I'm using my own slack client. One lesson learnt that, I probably shouldn't write my own slack client only because existing repo is 1 year old. 

There are few issue with slack client:
- I didn't ack() to stop slack from know the process request has been received
- I didn't do an extra check for client message id (duh). I forgot about the practices handling clients messages.
- I didn't get this history of the IM properly (eventually copied from the 1yo repo and let Cursor learn from it).

With the above, there is not more duplicate messages sent to the MCP-Bridge.

MCP-Bridge is all well , no fault!

Case closed.
